package dhcpd

var harpDHCPDConfBase = "# AUTO GENERATED FILE. DO NOT EDIT THIS FILE!\n\n" +
	"shared-network harp_network {\n" +
	"HARP_DHCPD_INCLUDE_STRINGS\n" +
	"}\n"
var includeStr = "include \"HARP_DHCPD_CONF_LOCATION\";"

var subnetConfBase = "# AUTO GENERATED FILE. DO NOT EDIT THIS FILE!\n\n" +
	"subnet HARP_DHCPD_SUBNET netmask HARP_DHCPD_NETMASK {\n" +
	"    range HARP_DHCPD_START_IP HARP_DHCPD_LAST_IP;\n" +
	"    next-server HARP_DHCPD_NEXT_SERVER;\n" +
	"    filename \"HARP_DHCPD_PXE_FILENAME\";\n" +
	"    option domain-name-servers HARP_DHCPD_DOMAIN_NAME_SERVER;\n" +
	"    option domain-name \"HARP_DHCPD_DOMAIN_NAME\";\n" +
	"    option subnet-mask HARP_DHCPD_NETMASK;\n" +
	"    option routers HARP_DHCPD_GATEWAY;\n" +
	"    min-lease-time HARP_DHCPD_MIN_LEASE_TIME;\n" +
	"    default-lease-time HARP_DHCPD_DEFAULT_LEASE_TIME;\n" +
	"    max-lease-time HARP_DHCPD_MAX_LEASE_TIME;\n" +
	"\n" +
	"    # node entries start here\n" +
	"HARP_DHCPD_NODES_ENTRIES" +
	"}\n"

var nodeEntry = "    host HARP_DHCPD_NODE_NAME {\n" +
	"        hardware ethernet HARP_DHCPD_NODE_PXE_MAC;\n" +
	"        fixed-address HARP_DHCPD_NODE_IP;\n" +
	"        filename \"HARP_DHCPD_PXE_FILENAME\";\n" +
	"    }\n\n"
